- .travis.yml
- deploy-docs.sh
Build isn't failing due to an wrong build script anymore. Still failing out of other reasons though.
> Fix Travis build script (travis has built in Rust support)

- src/server/mod.rs
the result has a ‘val_start_idx’ offset that should be added for slicing haystack properly
> fixes a panic! when searching from ‘val_start_idx’ in ‘haystack’

- Cargo.toml
- src/client/mod.rs
- tests/local.rs
This test does break the build but it does so on purpose, because the previous test did not actually verify that the request parsing was working correctly.
This might be overkill, but it will make sure everything works.
> Rewrite test to be more robust, fix testing on Windows (breaks build)

- src/server/mod.rs
I ended up with application/octet-stream with properly filled Content-Type
> content type value string needs trimming before `parse::<Mime>()`

- src/server/boundary.rs
- src/server/mod.rs
- in boundary.rs : just search for CRLF if there was chars before the
boundary. Maybe this could be passed as a searched prefix to the
BoundaryReader.
- in mod.rs : removed CRLF prefix (see above), and added systematic
line read after boundary to eat the CRLF, and check for multipart end
> Fix boundary corner cases suggestion

- Cargo.toml
- src/lib.rs
- src/local_test.rs
- src/server/boundary.rs
- src/server/buf_read.rs
- src/server/mod.rs
@nicolas-cherel 
No externally breaking changes that I can see right now.
I added a new test to make sure that it doesn't break on partial reads. Fixing the partial reads issue required copying `BufReader` from `std` and adding a method that reads more data into the non-empty buffer. I'll be drafting an RFC to have this method added to `BufReader` soon.
The test for Stable fails... because of APIs that have been stabilized since the last Stable release. So... while this is *technically* still compatible with Stable, it doesn't build on it right now. I don't know when the next release is because I don't keep track of the trains. RFC on what to do about this.
Closes #18.
> Fix boundary parsing on partial reads

- Cargo.toml
- src/client/mod.rs
- src/local_test.rs
- src/server/hyper.rs
- src/server/mod.rs
This is a minor breaking change, thus necessitating a version bump.
On the client-side, `Multipart::write_*()` methods now take and return `&mut self` instead of `self`, While this breaks method-chaining with `.send()`, which still requires by-value `self`, it is a general improvement on ergonomics, especially in loops.
On the server-side, `HttpRequest::is_multipart()` was removed, as it was superfluous. `HttpRequest::boundary()` got renamed to `multipart_boundary()` and gained a clarification on its semantics.
> Adjustments to client and server APIs

- src/server/boundary.rs
Just to mention it, I don’t know if something should be done for the
‘\r\n’ after the boundary ending. Since content after boundary is
supposed to be ignored, I don’t think it needs to be enforced, and does
not need any care about being consumed or not.
> Fix boundary ending

- src/client/lazy.rs
- src/server/mod.rs
The code is already squeaky clean, so clippy found only two very minor style nits. :+1:
> fixed two clippy warnings

- Cargo.toml
This crates does not need default ssl feature from hyper
Disable it allow to compile this crate with deps having
different openssl version from hyper 0.9
Cheers
> Disable hyper default features for openssl deps

- src/server/mod.rs
Due to the case-sensitive file representation on docs.rs
For sure, this one does not lack on windows systems -- but the documentation is mostly served on posix systems -- as you know and already said at #61
> Fixed link-typos in server/mod.rs

- Cargo.toml
The iron integration appears to still work at 0.5
> Bump the version of iron

- src/server/field.rs
This removes an unused, erroneous macro definition.
The macro definition compiles today due to https://github.com/rust-lang/rust/issues/39404, which will be fixed in https://github.com/rust-lang/rust/pull/39419.
> Remove unused macro definition

- src/lib.rs
`safemem` crate is used only if `server` feature is enabled, but `extern crate safemem` is written without `#[cfg(feature = "server")]`. This causes compilation error if I compile it without `server` feature.
```
cargo build --features 'client hyper' --no-default-features
```
```
error[E0463]: can't find crate for `safemem`
--> src\lib.rs:51:1
|
51 | extern crate safemem;
| ^^^^^^^^^^^^^^^^^^^^^ can't find crate
```
> Dependency to safemem is optional but required

- src/server/boundary.rs
This fixes #86 
It happens that somethimes multipart bodies have multiple `\r\n` before the next boundary, so it happened that multipart would remove the boundary only partially
Also I should note that commit ad3ceab does not fix the issue of #86 and only introduces a logic bug (because the first time the buffer will be always empty)
> Consume multiple \r\n when needed

- src/server/field.rs
I've encountered parsing errors when processing a request from [hackney](https://github.com/benoitc/hackney) using this crate, and I've tracked those down to it not accepting lowercase subpart headers.
If I interpret the standards correctly, MIME headers (such as Content-Type) as specified in [RFC 2045](https://tools.ietf.org/html/rfc2045) follow the definitions from RFC 822. The relevant parts are:
> [field       =  field-name ":" [ field-body ] CRLF](https://tools.ietf.org/html/rfc822#section-3.2)
> [field-name  =  1*<any CHAR, excluding CTLs, SPACE, and ":">](https://tools.ietf.org/html/rfc822#section-3.2)
> [CHAR        =  \<any ASCII character>](https://tools.ietf.org/html/rfc822#section-3.3)
> ...
> [Except as noted, alphabetic strings may be represented in  any combination of upper …
> Compare header names case-insensitively

- .travis.yml
- Cargo.toml
- README.md
Attempt number two :)
Before this patch, multipart got into an impossible sitation with it's dependencies. It errs with:
```
error: failed to select a version for `lazy_static`.
... required by package `multipart v0.15.4`
versions that meet the requirements `>= 1.0, < 1.2.0` are: 1.1.0, 1.0.2, 1.0.1, 1.0.0
all possible versions conflict with previously selected packages.
previously selected package `lazy_static v1.2.0`
... which is depended on by `ring v0.13.5`
... which is depended on by `cookie v0.11.0`
... which is depended on by `rocket_http v0.4.0`
... which is depended on by `rocket v0.4.0`
... which is depended on by `multipart v0.15.4
```
This is due to ring 0.13.3 bumping lazy_static to 1.2.0 to avoid a [soundness bug](https://github.com/rust-lang-nursery/lazy-static.rs/issues/117 …
> Use lazy_static 1.2.0, remove twoway/pcmp and require rust 1.24.1+

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/server/iron.rs
- src/server/save.rs
According to the tempdir repository, tempdir has been deprecated
and replaced with tempfile:
https://github.com/rust-lang-deprecated/tempdir#deprecation-note
The current api publicly exposes the `tempdir::TempDir` type,
so this patch is a breaking change to the public api, so I bumped
the major version in the Cargo.toml file.
> Switch from tempdir to tempfile

- src/client/mod.rs
Seems like hyper is reading until it sees `\r\n`, and since that's not being sent, I get 
```
ERROR 2018-11-20T08:47:28Z: actix_web::pipeline: Error occurred during request handling, status: 500 Internal Server Error Multipart stream is incomplete
```
This just adds the `\r\n` to the end so hyper has no problem seeing it.
> Fix incomplete multipart problem

- Cargo.toml
rand<0.7 depends on rand_core 0.3 which suffers from https://rustsec.org/advisories/RUSTSEC-2019-0035
cargo test passes but I'll be happy run additional tests if you can advise me which ones/how.
> Bump rand to 0.7 to address RUSTSEC-2019-0035
